[package]
name = "websocket-echo"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
rust-api = { path = "../..", features = ["websocket"] }
tokio = { version = "1", features = ["full"] }
